version: "3.4"
volumes:
  bundle-volume:
  shared-volume:
networks:
  default:
    external:
      name: ezcater-development-network
x-environment: &default-environment
  BUNDLE_EZCATER__JFROG__IO:
  BOOTSNAP_CACHE_DIR: /usr/src/shared/bootsnap
  PRYRC: /usr/src/app/.docker-pryrc
  BUNDLE_IGNORE_CONFIG: 1
  BUNDLE_DISABLE_SHARED_GEMS: "true"
  POSTGRES_HOST: ezhackathon-db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
x-service: &default-service
  build:
    context: .
    args:
    - BUNDLE_EZCATER__JFROG__IO
  volumes:
  - .:/usr/src/app
  - bundle-volume:/usr/local/bundle:delegated
  - shared-volume:/usr/src/shared:delegated
  tty: true
  stdin_open: true
  depends_on:
  - ezhackathon-db
services:
  ezhackathon-db:
    container_name: ezhackathon_ezhackathon-db_1
    image: postgres:13.2-alpine
    volumes:
    - $HOME/postgresql/13.2/data/ezhackathon:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password
  ezhackathon-web:
    <<: *default-service
    container_name: ezhackathon_ezhackathon-web_1
    environment:
      <<: *default-environment
      IGNORE_KAFKA:
      IGNORE_SCHEMA_REGISTRY:
    command: bin/start
    ports:
    - 127.0.0.1:28076:28076
